[package]
name = "client"
version = "0.1.0"
authors = ["Steven Joruk <steven@joruk.com>"]
edition = "2018"
publish = false

[dependencies]
futures = { version = "0.3" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
xpc-connection = { path = "../../xpc-connection" }
